### ISSUE TITLE
openSimIO for research applications?

### ISSUE THREAD

**Issue by felipetallabs** [condac/openSimIO#34]
Hello,
 I have a question for condac, or anyone who can help, (Thanks)
 I would like to know if you think I could use openSimIO to send data from a specific dataref from       X Plane 10 to arduino. This is for a project I am doing that uses aerodynamic information to inform the  pilot regarding the status of airplane during flight, using a vest with vibration stimulators. but for that I need to obtain data from a specific dataref:
Sim/flightmodel2/wing/elements/element_is_stalled?
I do not need to send any data to x plane only to send data to arduino.
thanks
Felipe

**Comment by condac** [comment]
Yes you can send data to arduino also. If you look at the exemple config: https://github.com/condac/openSimIO/blob/master/xplane_plugin/example_config_usb.txt#L17 
This will turn the builtin led on or off depending on the status of the switch. You can do this with any dataref. The dataref in your question is also an array so you need to specify the index in the array for what wing element you are looking at.
 `1.0.D13;0;DO_BOOL;0;0;0;1;sim/flightmodel2/wing/elements/element_is_stalled[0];0;0;1;0;`
You also have the option to output PWM signal based on analog datarefs:
 `1.0.D5;0;AO_PWM;0;0;0;255;sim/cockpit2/annunciators/stall_warning_ratio;0;0;1;0;`
