### ISSUE TITLE
Serial config not working!

### ISSUE THREAD

**Issue by ryucz** [condac/openSimIO#38]
While trying to send config, i get message "Error! converting config line 1;s;\\.\COM1"

Additional research comes to this:

pins.c @ line 53 
`if((line[0] == '#') || (line[0] == '\r') || (line[0] == '\n') )`

is missing
`line[0] == '/'`

**Comment by philhynes01** [comment]
I had this same issue, I added the missing "\" to the start of the string \1;s;\.\COM1 and it worked

**Comment by posixPilot** [comment]
I patched pins.c like this, which is what I think ryucz is referring to:

```
53c53
<   if((line[0] == '#') || (line[0] == '\r') || (line[0] == '\n') ) {
---
>   if((line[0] == '#') || (line[0] == '\r') || (line[0] == '\n') || (line[0] == '/') ) {

```

**Comment by condac** [comment]
I have not been able to see why this will prevent the program from working correctly, in my test it just throws an error message when reading the config but still operates normal. This is just hiding the error message and not changing the outcome so if the program is not working this will probably not fix the issue. 
But there should be no error messages during normal operations just a bit confused to why it would fix an issue.

**Comment by posixPilot** [comment]
Hi Condac,

> But there should be no error messages during normal operations just a bit confused to why it would fix an issue.

You are probably correct, but I think any user would assume the system couldn't work with this error.  At least that is what I assumed.  I believe the serial port config is silently read in another part of the code, but I did not put the time in to find out how that works.  Yes, this does just hide the error, but the error is apparently not relevant to this part of the code anyways.  It is possible that the only thing this fixed was my perception of broken.

  Thanks
  Mike
